# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586b10d7b5a7cfe6be813c3b27a4867961c0e78e1826c478682d3a6ac4e26327372d7e09e336db2586a25e9b46668253ebe9afa500d952eaa4e1e9d23e7d3365

test:
  secret_key_base: ce436d84822c3e804b889f23092be8424c3e5345b1ef7c657fd6284f056e3a852f541fc013f81e994c0a1b2e335bc866a65a39d54d9b1b0a3f96a868bc449b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
